apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
spec:
  source:
    path: apps/dev/
    repoURL: "https://github.com/rahulinux/sde-gitops"
    targetRevision: main
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
