apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

patches:
  - patch: |-
      - op: add
        path: /metadata/finalizers
        value:
          - resources-finalizer.argocd.argoproj.io
    target:
      kind: Application
      group: argoproj.io
      version: v1alpha1

resources:
  - kube-ops-view/application.yaml
  - game/application.yaml
